# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PWD }}
          port: ${{ secrets.SSH_PORT }} 
          script: |
            export repo=${{ secrets.REPOS }}
            export socket=${{ secrets.SOCKET_URL }}
            sh deploy.sh
        
        
                 
