# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy server
        uses: appleboy/ssh-action@master
        env:
          repo: ${{ secrets.REPOS }}
          socket: ${{ secrets.SOCKET_URL }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PWD }}
          port: ${{ secrets.SSH_PORT }} 
          envs: repo,socket
          script: sh deploy.sh
                 
